sp500_companies = {
    "Apple Inc.": "AAPL",
    "Microsoft Corporation": "MSFT",
    "Amazon.com, Inc.": "AMZN",
    "Meta Platforms, Inc.": "META",
    "Alphabet Inc.": "GOOGL",
    "Berkshire Hathaway Inc.": "BRK.B",
    "NVIDIA Corporation": "NVDA",
    "Tesla, Inc.": "TSLA",
    "JPMorgan Chase & Co.": "JPM",
    "Johnson & Johnson": "JNJ",
    "UnitedHealth Group Incorporated": "UNH",
    "Visa Inc.": "V",
    "Exxon Mobil Corporation": "XOM",
    "Procter & Gamble Company": "PG",
    "Home Depot, Inc.": "HD",
    "Mastercard Incorporated": "MA",
    "Chevron Corporation": "CVX",
    "Pfizer Inc.": "PFE",
    "Broadcom Inc.": "AVGO",
    "The Walt Disney Company": "DIS",
    "Bank of America Corporation": "BAC",
    "AbbVie Inc.": "ABBV",
    "Costco Wholesale Corporation": "COST",
    "Coca-Cola Company": "KO",
    "PepsiCo, Inc.": "PEP",
    "Merck & Co., Inc.": "MRK",
    "Walmart Inc.": "WMT",
    "Cisco Systems, Inc.": "CSCO",
    "Intel Corporation": "INTC",
    "Oracle Corporation": "ORCL",
    "Thermo Fisher Scientific Inc.": "TMO",
    "McDonald's Corporation": "MCD",
    "Salesforce, Inc.": "CRM",
    "Comcast Corporation": "CMCSA",
    "Netflix, Inc.": "NFLX",
    "The Goldman Sachs Group, Inc.": "GS",
    "Capital One Financial Corporation": "COF",
    "American Express Company": "AXP",
    "Advanced Micro Devices, Inc.": "AMD",
    "QUALCOMM Incorporated": "QCOM",
    "PayPal Holdings, Inc.": "PYPL",
    "Wells Fargo & Company": "WFC",
    "Boeing Company": "BA",
    "United Parcel Service, Inc.": "UPS",
    "Nike, Inc.": "NKE",
    "NextEra Energy, Inc.": "NEE",
    "Lockheed Martin Corporation": "LMT",
    "Morgan Stanley": "MS",
    "3M Company": "MMM",
    "Raytheon Technologies Corporation": "RTX",
    "Philip Morris International Inc.": "PM",
    # ... you can expand as needed
}
